### ISSUE TITLE
CSS "load" order inconsistency between on-the-fly/dev mode and (sfx)bundle mode.

### ISSUE THREAD

**Issue by andreasgrimm** [systemjs/plugin-css#18]
using the non-bundling, on-the-fly transpilation mode, changing the order of explicit CSS import statements, changes the load order accordingly (which can be observed in DevTools' Network tab). For instance

```javascript
import 'bootstrap/css/bootstrap.css!css';
import 'bootstrap/css/bootstrap-theme.css!css';
import 'angular-xeditable/dist/css/xeditable.css!css';
```

loads/applies `xeditable.css` after the bootstrap CSS was loaded and applied, whereas

```javascript
import 'angular-xeditable/dist/css/xeditable.css!css';
import 'bootstrap/css/bootstrap.css!css';
import 'bootstrap/css/bootstrap-theme.css!css';
```

would do it vice versa.

But as soon as you bundle, you can't rely on that order anymore.

For all the CSS you have control over, you of course would not need to rely on CSS load order but rather implement your CSS overrides by applying CSS specificity.
But it's a different use case when you want to use a vendor lib that relies on CSS load order to override CSS from another vendor lib (instead of using CSS specificity).

**Comment by guybedford** [comment]
Sure - yes we should aim to ensure the order is maintained in bundling.

**Comment by AdamBurgess** [comment]
In my tests even the on-the-fly transpilation doesn't work in order.
Take this example: if the main file you import looks like this:

```
import './1.css!'
import './styles2'
import './3.css!'
```

and styles2.js is `import './2.css!'`

I see the order in the HTML is 1, 3, 2. (and not 1, 2, 3)

**Comment by AdamBurgess** [comment]
I can't seem to reproduce this (I'm using the source from my fork, though)
The bundle's `loads` array is always in the same order as the import order.

**Comment by andreasgrimm** [comment]
In `app.css` I override e.g. the `font-family`

**Comment by AdamBurgess** [comment]
What browser are you using (for on-the-fly)? I'm using chrome 43. Both on-the-fly and bundling work as expected. I'm using my fork here, but I don't get them out-of-order with the current plugin either.
```javascript
import 'angular-material/angular-material.css!AdamBurgess/plugin-css';
import 'app.css!AdamBurgess/plugin-css';
```

where my app.css contains
```css
button, select, html, textarea, input {
    font-family: "Custom Font Here";
}
```

the output build.css looks something like:
```css
/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v0.8.3
 */*,:after,:before{box-sizing:border-box} ..... lots of css ..... button,html,input,select,textarea{font-family:"Custom Font Here"}
```
in my fork, since clean-css is used to merge the css, the `original button,html,input,select,textarea` `font-family` declaration is removed completely (deduplicated)
