### ISSUE TITLE
Bug in css minification process

### ISSUE THREAD

**Issue by marek-ganko** [systemjs/plugin-css#27]
While creating bundle with JSPM with options `"buildCSS": true`, it seems that css plugin cuts out too many characters which leads to broken styles.
For example:
```css
#todo-list li .toggle:after {
	content: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="-10 -18 100 135"><circle cx="50" cy="50" r="50" fill="none" stroke="#ededed" stroke-width="3"/></svg>');
}
```
is minified into this:
```css
#todo-list li .toggle:after{content:url(data:image/svg+xml;utf8,<svg xmlns=http://www.w3.org/2000/svg width=40 height=40 viewBox=-10 -18 100 135><circle cx=50 cy=50 r=50 fill=none stroke=#ededed stroke-width=3/></svg>)}
```
