### ISSUE TITLE
error "Please check the validity of the CSS block ..." when bundling CSS with "@font-face"

### ISSUE THREAD

**Issue by andreasgrimm** [systemjs/plugin-css#7]
In my main CSS file starting from line 1 I have

```css
@font-face {
  font-family: 'foo';
  src: url('bar');
...
  font-weight: normal;
  font-style: normal;
}
```

Now when bundling with jspm I got the following error:

`Please check the validity of the CSS block starting from the line #1`

If I remove `@font-face` it works just fine.
