### ISSUE TITLE
System.delete("file.css") should remove link from head

### ISSUE THREAD

**Issue by alexisvincent** [systemjs/plugin-css#81]
System.delete("file.css") should remove link from head. When hot reloading css with capaj/systemjs-hot-reloader. 

Currently the delete does nothing. And then the css file is injected. So what ends up happing is actually a minimal overwrite.

a.css
```css
lol {
  background: blue;
  color: green;
}
```

a2.css
```css
lol {
  background: blue;
}
```

The expectation is that the color property is no longer being specified. But it is.
